### ISSUE TITLE
Log-In using a regular account

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#44]
1. As a user
2. i want to log-in to the application using the regular account that i previously created
3. so that i can access the application

Acceptance Criteria:
- Includes fields to enter username/e-mail and password
- Includes button to proceed with login
- Once button is pressed user is forwarded to main screen

Backend Criteria: 
- System compares entered credentials with user database
- If credentials are invalid, system will let the user know that he entered the wrong credentials
- If credentials are valid, user is lead to the next screen within the app

**Comment by s-kruschel** [comment]
- [ ] Embedd the whole container into a ScrollView. 
- [ ] The "Willkommen zurück" is not centered.
- [ ] Opacity in the input field should be black as soon as the user entered something.
