### ISSUE TITLE
Edit personal information

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#48]
1. As a user
2. i want to be able to edit my personal information like name, e-mail address and phone number
3. so that i can make changes in my profile

Acceptance Criteria:
- Includes an edit button
- Includes a field for name, last name, e-mail
- Includes a save button
- Once save button is pressed, entered information appear on the screen as set information

(This is valid, even when user logged in with Facebook (etc.), because name and e-mail should be saved anyway)

**Comment by richmandlx** [comment]
Acceptance Criteria should be satisified with 684a0c61dd46e341b69af43255a5294335f3431d
The displayed data is mocked with a service class.
The basic business logic is implemented without backend access (can be done later).
I need to look into methods for react to give visual feedback (alot of the functions called could possibly fail, how do we tell the user? have some sort of status bar on top of all components?)

**Comment by richmandlx** [comment]
With the most recent commit I updated the graphics of this screen so that it fits to the Create Account Screen and looks a lot better than previously.
