### ISSUE TITLE
Decision on Framework (Backend)

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#49]

**Comment by richmandlx** [comment]
We will require a pretty standard backend that provides an API / Database.
The Backend is all about passing and processing data and there isn't one framework that will be the best. It's more about the personal preference of the software developers.

Here are some of the most popular choices:

If we go with python as programming language, there are Flask and Django.
Flask offers a lot less core functionality compared to Django but is extendable. This means if we use flask we would have to use additional packages for database access (like sqlalchemy) and authentication. Django already has support for database access and authentication stuff.

For java as programming language there is the very popular Spring Framework that supports building a RESTful API including persistence.

Using javascript as programming language we could go for the ExpressJs framework.
