### ISSUE TITLE
Know Where the Bike is Stored

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#57]
## User story
1. As a user
2. I want to see in which bike nest i parked my bike
3. So that i can find it again

## Acceptance criteria
* Includes map with a focus on the bike nest that user parked the bike at (location can be arbitrary for front end showcase)
* Includes users location on the map (depends on how you want implement it, if not possible, leave it out)
* Location tag can be pressed, a secondary, smaller window opens with additional information about the bike nest
* Includes button to request navigation to the selected location

For further input please refer to feature request: "Find Bike Nest"

**Comment by elenagaytan** [comment]
To do : 

- [ ] add functionality for buttons 
- [ ] edit style 
- [ ] rename this page
