### ISSUE TITLE
Backend Research

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#60]
Competitor analysis, what services to we need, tech stack clarification, research for use cases: create / activate account and login

**Comment by NikoBele1** [comment]
## Findings
 C4 Model for architecture and architecture documentation
https://c4model.com/
structures a systemin
- context: highest level of abstraction, describes value creation from elements
- containers:  application or a data store
- components: grouping of related functionality encapsulated behind an interface
- code: optional

Microservice architecture
![image](https://user-images.githubusercontent.com/32575893/117849690-dbeb7300-b284-11eb-9891-f034e0729184.png)

Microservice communication
https://blog.logrocket.com/methods-for-microservice-communication/
- HTTP communication (direct call)
- Message communication (subscriber - listener based, message decription needed)
- Event-driven communication (like message, but dont need knowledge of message structure)
