### ISSUE TITLE
Find a date for a Follow-Up with Jacob

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#71]

**Comment by richmandlx** [comment]
According to Jacob, the Backend Architecture is better now.
Follow up meeting is planned for Monday Afternoon (maybe 16:00).

**Comment by richmandlx** [comment]
Can this be closed @LukasMeister ?
We already held the meeting and jacob thinks our architecture looks good now.

**Comment by LukasMeister** [comment]
Yes, this should have been in the task archive as far as i remember. Thanks!
